### ISSUE TITLE
sample output

### ISSUE THREAD

**Issue by gsaray101** [flashdba/scripts#2]
hi, do you have sample output? Does it output it into time series tabular format? it is great script, thanks for sharing this with the world!!

**Comment by flashdba** [comment]
Jeez sorry but you catch me on vacation with no access to anything other
than my email. Wasn't there some sample output on my Flashdba.com site?

On Friday, 12 February 2016, gsaray101 notifications@github.com wrote:

> hi, do you have sample output? Does it output it into time series tabular
> format? it is great script, thanks for sharing this with the world!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/flashdba/scripts/issues/2.

## 

-- flashdba
http://flashdba.com
