### ISSUE TITLE
Return character in bc -l on cygwin env

### ISSUE THREAD

**Issue by jaymayers** [flashdba/scripts#3]
Couldn't get out of box script to working. When setting some of the variables like REDO_WRITE_THROUGPUT, a \n was appended and thus erroring out on bc -l.

bc: Syntax error on line 1 of standard input
+0.005)/1=2; (0.00536
                                    ^

Fix by replacing all "bc -l" with "bc -l | sed 's/[^[:digit:]]//g'"

%s/bc -l/bc -l | sed 's\/[^[:digit:]]\/]/g'/g

**Comment by flashdba** [comment]
Are you able to supply one of the AWR reports which caused this issue in the first place?
