### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by MaheshwarReddyGade** [flashdba/scripts#4]
I tried it but i'm getting an error :

awr-parser.sh: line 1793: syntax error near unexpected token `('
awr-parser.sh: line 1793: `     echoprt "               Read Throughput (MiB/sec) = $READ_THROUGHPUT"'
[oracle@server1 oracle]$

I downloaded from https://raw.githubusercontent.com/flashdba/scripts/master/awr-parser.sh

**Comment by flashdba** [comment]
Please re-run with the -X flag to see extremely verbose debug information, then cut and paste 5 lines either side of the error message back here.

**Comment by MaheshwarReddyGade** [comment]
[oracle@server1 oracle]$ sh -x awr-parser.sh awr*.txt > tunedbperftests.csv
+ AWRSCRIPT_VERSION=1.02
+ AWRSCRIPT_LASTUPDATE=04/12/2016
+ ERRORCNT=0
+ FILECNT=0
+ HEADERROW=1
+ SILENT=0
+ PRINT_REPORT_INFO=0
+ VERBOSE=0
+ DEBUG=0
+ EXIT_SUCCESS=0
+ EXIT_PARTIAL_SUCCESS=1
+ EXIT_FAILURE=2
+ AWR_NOTFOUND=0
+ AWR_PENDING=1
+ AWR_FOUND=2
+ OLD_AWR_SECTION_TERMINATOR_BY_WORD=-------------------------------------------------------------
+ OLD_AWR_SECTION_TERMINATOR_BY_LINE='          -------------------------------------------------------------'
+ NEW_AWR_SECTION_TERMINATOR_BY_WORD=------------------------------------------------------
+ NEW_AWR_SECTION_TERMINATOR_BY_LINE='                          ---------------------------------------------'
+ ENDCHAR=
awr-parser.sh: line 1793: syntax error near unexpected token `('
awr-parser.sh: line 1793: `     echoprt "               Read Throughput (MiB/sec) = $READ_THROUGHPUT"'
[oracle@server1 oracle]$

**Comment by MaheshwarReddyGade** [comment]
[oracle@USAESGURP1ORA1 oracle]$ ./awr-parser.sh -X -v awr*.txt > tunedbperftests.csv
./awr-parser.sh: line 1793: syntax error near unexpected token `('
./awr-parser.sh: line 1793: `   echoprt "               Read Throughput (MiB/sec) = $READ_THROUGHPUT"'
[oracle@USAESGURP1ORA1 oracle]$

**Comment by MaheshwarReddyGade** [comment]
[oracle@server1 oracle]$ ./awr-parser.sh -X -v awr*.txt > tunedbperftests.csv
./awr-parser.sh: line 1793: syntax error near unexpected token `('
./awr-parser.sh: line 1793: `   echoprt "               Read Throughput (MiB/sec) = $READ_THROUGHPUT"'
[oracle@server1 oracle]$

**Comment by flashdba** [comment]
That doesn't appear to be the output I requested - I need the information send to stderr. And I asked for 5 lines either side of the error message.

Rerun the command like this:

./awr-parser.sh -X -v awr*.txt > tunedbperftests.csv 2> debug.log

The look at the debug logfile, find the syntax error message and cut and paste it along with the five lines before it and the five lines after it.
