### ISSUE TITLE
awr_generate.sql

### ISSUE THREAD

**Issue by YairPR** [flashdba/scripts#6]
REM Created by user SYS on psbdoprd11.pps.com.pe at 04-AUG-2021 12:52
SP2-0023: String not found.
SP2-0023: String not found.
SP2-0023: String not found.
SP2-0023: String not found.
SP2-0023: String not found.
SP2-0023: String not found.
SP2-0734: unknown command beginning "v_awr_repo..." - rest of line ignored.
SP2-0734: unknown command beginning "v_report_s..." - rest of line ignored.
SP2-0023: String not found.
SP2-0734: unknown command beginning "CURSOR c_s..." - rest of line ignored.
 and s.snap_id <= c_end_snap_id
                  *
ERROR at line 10:
ORA-00904: "C_END_SNAP_ID": invalid identifier

**Comment by flashdba** [comment]
Re-added missing DECLARE statement #embarrassing
